#!/bin/sh

# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done

echo "Git pre commit hock"

. ./.env/Scripts/activate
if test $? != 0
then
    echo -e '\033[31mError in git pre push hock - ./.env/Scripts/activate\033[0m'
    exit 1
fi

echo "python dir"
python -m pip -V

python ./scripts/lint_tools.py --jupyter-verify
exit_code=$?
if test $exit_code != 0
then
    echo -e '\033[31mError in pre commit hock - ./scripts/lint_tools.py\033[0m'
fi

deactivate

exit $exit_code